### ISSUE TITLE
Using on route -> template URLs?

### ISSUE THREAD

**Issue by jackmcdade** [statamic/seo-pro#4]
How would somebody set the meta data for a non-page/entry driven url? Would something like this work? Or can/does it fall back to the cascade at all?

```
/landing:
  template: landing-page
  seo:
    title: Super Cool Landing Page
```
