### ISSUE TITLE
Staging site not showing all sections

### ISSUE THREAD

**Issue by sevfurneaux** [statamic/seo-pro#48]
On our `.staging` site, the **Seo Pro** section in the cp is not showing all the plugin pages:

<img width="169" alt="screen shot 2018-11-13 at 17 22 27" src="https://user-images.githubusercontent.com/1056416/48427306-c0ad5480-e768-11e8-9e5c-334a285d91ce.png">

Whilst locally, it is showing all the sections:

<img width="209" alt="screen shot 2018-11-13 at 17 23 13" src="https://user-images.githubusercontent.com/1056416/48427339-d1f66100-e768-11e8-8b25-01e98d38f4a5.png">

We have purchased the license. Is this because the site is `.staging` and not the license's domain?

**Comment by jasonvarga** [comment]
What URL do you have set in system.yaml? If it doesn't match correctly, the navigation active state logic doesn't pick it up.

**Comment by sevfurneaux** [comment]
We have two locales in system.yaml:

```
locales:
  de:
    full: de_DE
    name: German
    url: '{env:SITE_URL}'
  en:
    full: en_US
    name: English
    url: '{env:SITE_URL}/en/'
```

The `env:SITE_URL` is then setup in Laravel Forge.
