### ISSUE TITLE
CP error when assigning social image from field

### ISSUE THREAD

**Issue by mikemartin** [statamic/seo-pro#97]
After setting the section default image field, the following error is shown at 
/cp/seo-pro/section-defaults/collections/articles/edit
https://flareapp.io/share/LPdn9z5O#F71

`image: '@seo:photo'`

**Collection config:**
```
title: Articles
template: articles/show
layout: layout
mount: c6d769d3-f172-4e91-91f3-c0421ca2e5bb
taxonomies:
  - categories
revisions: false
route: '/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
inject:
  seo:
    image: '@seo:photo'
```

**Article blueprint**:
```
title: Article
sections:
  main:
    display: Main
    fields:
      -
        handle: description
        field:
          type: textarea
          localizable: false
          listable: hidden
          display: Description
      -
        import: content
  cta:
    display: CTA
    fields:
      -
        import: cta
        prefix: cta_
  sidebar:
    display: Sidebar
    fields:
      -
        handle: author
        field:
          type: users
          display: Author
          default: current
          localizable: true
          max_items: 1
      -
        handle: photo
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          listable: hidden
          display: Photo
```

**SEO Pro Asset config:**
```
<?php

return [

    'assets' => [
        'container' => 'assets',
        'open_graph_preset' => [
            'w' => 1200,
            'h' => 1200,
            'fit' => 'crop',
        ],
    ],

];
```
